name: readme_creator
description: "A tool to generate Markdown README files"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  # Firebase Core & Services
  firebase_core: ^3.10.1
  firebase_auth: ^5.5.0
  cloud_firestore: ^5.6.3
  firebase_analytics: ^11.4.1

  # Common UI & Logic
  cupertino_icons: ^1.0.8
  uuid: ^4.5.2
  provider: ^6.1.5+1
  shared_preferences: ^2.5.4
  json_annotation: ^4.9.0
  flutter_highlight: ^0.7.0
  http: ^1.6.0
  archive: ^4.0.7
  file_picker: ^10.3.8
  flutter_colorpicker: ^1.1.0
  tutorial_coach_mark: ^1.3.3
  markdown: ^7.3.0
  printing: ^5.14.2
  pdf: ^3.11.3
  path_provider: ^2.1.1
  share_plus: ^7.2.1
  font_awesome_flutter: ^10.12.0
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  google_fonts: ^6.3.3
  google_generative_ai: ^0.4.7
  url_launcher: ^6.3.2
  path: ^1.9.1
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  flutter_markdown: ^0.7.7+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.10.4
  json_serializable: ^6.11.3

flutter:
  generate: true
  uses-material-design: true
